BEGIN;

ALTER TABLE orders
    ALTER COLUMN id TYPE INTEGER,
    ALTER COLUMN user_id TYPE INTEGER,
    ALTER COLUMN total TYPE INTEGER;
    
ALTER TABLE line_items
    ALTER COLUMN id TYPE INTEGER,
    ALTER COLUMN order_id TYPE INTEGER,
    ALTER COLUMN item_id TYPE INTEGER,
    ALTER COLUMN price TYPE INTEGER,
    ALTER COLUMN quantity TYPE INTEGER;

ALTER TABLE items
    ALTER COLUMN id TYPE INTEGER,
    ALTER COLUMN price TYPE INTEGER,
    ALTER COLUMN stock TYPE INTEGER;

COMMIT;

