BEGIN;

ALTER TABLE items
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN price TYPE BIGINT,
    ALTER COLUMN stock TYPE BIGINT;

ALTER TABLE line_items
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN order_id TYPE BIGINT,
    ALTER COLUMN item_id TYPE BIGINT,
    ALTER COLUMN price TYPE BIGINT,
    ALTER COLUMN quantity TYPE BIGINT;

ALTER TABLE orders
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN user_id TYPE BIGINT,
    ALTER COLUMN total TYPE BIGINT;

COMMIT;

